name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          publish_branch: output
          github_token: ${{ secrets.GITHUB_TOKEN }}
